openapi: 3.0.0
info:
  version: "1.0.0"
  title: "chestbit backend"
  description: "chestbit API"
paths:
  "/login":
    post:
      description: "sig in a user from email and password"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/log-in"
      responses:
        201:
          description: valid user cred
          content:
            text/plain:
              schema:
                type: string
                description: the Bearer token
                example: Bearer token
        400:
          description: bad request
  "/newUser":
    post:
      description: "register a new user"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/newUser"
      responses:
        201:
          description: user is successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        400:
          description: bad request
  "/logout":
    post:
      description: log out user
      security:
        - bearerAuth: []
      responses:
        200:
          description: OK

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    log-in:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - mail
        - password
    newUser:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        password_confirmation:
          type: string
          format: password
        firstname:
          type: string
        is_admin:
          type: boolean
        lastname:
          type: string
        address:
          type: string
        country:
          type: string
      required:
        - mail
        - password
        - password_confirmation
        - firstname
        - is_admin


